version: '3'

volumes:
  mimir-1-data:
  mimir-2-data:
  mimir-3-data:
  minio-data:

services:

  minio:
    image: minio/minio
    entrypoint: [""]
    command: ["sh", "-c", "mkdir -p /data/mimir && minio server --quiet /data"]
    environment:
      - MINIO_ROOT_USER=mimir
      - MINIO_ROOT_PASSWORD=supersecret
    volumes:
      - minio-data:/data

  load-balancer:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "mimir-1"
      - "mimir-2"
      - "mimir-3"
    ports:
      - 9009:9009

  mimir-1:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir-1
    depends_on:
      - minio
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      # - ./config/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
      - mimir-1-data:/data

  mimir-2:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir-2
    depends_on:
      - minio
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      # - ./config/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
      - mimir-2-data:/data

  mimir-3:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir-3
    depends_on:
      - minio
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      # - ./config/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
      - mimir-3-data:/data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/tmp:/prometheus
      - ./prometheus/config:/etc/prometheus
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    depends_on:
      - "mimir-1"
      - "mimir-2"
      - "mimir-3"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/tmp:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

  alertmanager:
    image: prom/alertmanager:v0.25.0
    ports:
      - "9093:9093"
    volumes:
      - ./alert-manager/tmp:/data
      - ./alert-manager/config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alert-manager/config:/config
    command: --config.file=/config/alertmanager.yml

  container1:
    build: ./container1
    ports:
      - "5000:5000"  # Replace 3001 with the port your first Node.js application listens on.
      - "5001:5001"
    volumes:
      - /var/lib/docker:/var/lib/docker
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.137.1:3100/loki/api/v1/push"

  container2:
    build: ./container2
    ports:
      - "7000:7000"
      - "6001:6001"
    volumes:
      - /var/lib/docker:/var/lib/docker
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.137.1:3100/loki/api/v1/push"

  container3:
    build: ./container3
    ports:
      - "4000:4000"
      - "4001:4001"
    volumes:
      - /var/lib/docker:/var/lib/docker
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.137.1:3100/loki/api/v1/push"

  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki-data:/loki
    networks:
      - loki
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:latest
    volumes:
      - "/var/log:/var/log"
      - "/var/lib/docker/containers:/var/lib/docker/containers"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./promtail-config.yaml:/etc/promtail/config.yaml"
    command: "-config.file=/etc/promtail/config.yaml"
    networks:
      - loki

  

networks:
  loki: