positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://192.168.137.1:3100/loki/api/v1/push
scrape_configs:
  - job_name: docker
    pipeline_stages:
      - docker: {}
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log