global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'rules.yml'
alerting:
  alertmanagers:
    - scheme: http
    - static_configs:
        - targets: ['192.168.137.1:9093']


scrape_configs:
  - job_name: 'container1'
    static_configs:
      - targets: ['192.168.137.1:5001']  # Replace 'port1' with the port of your first Node.js application.
  - job_name: 'container2'
    static_configs:
      - targets: ['192.168.137.1:6001']  # Replace 'port2' with the port of your second Node.js application.
  - job_name: 'container3'
    static_configs:
      - targets: ['192.168.137.1:4001']  # Replace 'port3' with the port of your third Node.js application.

