route:
  receiver: tutorial-alert-manager
  repeat_interval: 1m
receivers:
  - name: 'tutorial-alert-manager'
    email_configs:
      - to: 'email@gmail.com'
        from: 'email@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'email@gmail.com'
        auth_identity: 'email@gmail.com'
        auth_password: 'app password'
        send_resolved: true
